### ISSUE TITLE
Feature Request: Private ManagedObjectContext with new PersistentStoreCoordinator

### ISSUE THREAD

**Issue by ParmeshwarBayappu** [mmorey/MDMCoreData#30]
For the purpose of import/sync in background I see the value in including a method to return a new ManagedObjectContext of NSPrivateQueueConcurrencyType with new instance of PersistentStoreCoordinator (same store and model as the main managedObjectContext). 

You have implemented this in your MDMHPCoreData library. Including this in the MDMCoreData library would serve the typical need for this and promote the best practice of doing large imports in the background without blocking the UI during read operations. 
(https://github.com/mmorey/MDMHPCoreData/blob/master/MDMHPCoreData/MDMHPCoreData/model/MDMPersistenceStack.m - newPrivateManagedObjectContextWithNewPersistentStoreCoordinator)

**Comment by mmorey** [comment]
@ParmeshwarBayappu sounds like a good idea. Can you submit a pull request?

**Comment by ParmeshwarBayappu** [comment]
Will do. This will be my first attempt at open source contribution - so advance thanks for the patience.

**Comment by mmorey** [comment]
@ParmeshwarBayappu I merged your PR. When you get a chance do you think you could you submit a separate PR to update the README showing off this new feature?

**Comment by ParmeshwarBayappu** [comment]
Will do this weekend.

**Comment by malhal** [comment]
Once you have this then you can remove newPrivateChildManagedObjectContext since that doesn't solve the problem it was designed for. The issue is it inserts into the context on a thread but when it saves, then it blocks the main thread as it merges the changes back into the main context, and then it blocks the main thread again when saved to the store. Child contexts are only needed for scratch pad use.

**Comment by ghost** [comment]
> For the purpose of import/sync in background I see the value in including a method to return a new ManagedObjectContext of NSPrivateQueueConcurrencyType with new instance of PersistentStoreCoordinator (same store and model as the main managedObjectContext).
> 
> You have implemented this in your MDMHPCoreData library. Including this in the MDMCoreData library would serve the typical need for this and promote the best practice of doing large imports in the background without blocking the UI during read operations. (https://github.com/mmorey/MDMHPCoreData/blob/master/MDMHPCoreData/MDMHPCoreData/model/MDMPersistenceStack.m - newPrivateManagedObjectContextWithNewPersistentStoreCoordinator)
